### ISSUE TITLE
No license text included in distributions

### ISSUE THREAD

**Issue by AdamWill** [tchwork/jsqueeze#10]
I'm packaging JSqueeze for Fedora. The [Fedora licensing guidelines](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines) note:

"In cases where the upstream has chosen a license that requires that a copy of the license text be distributed along with the binaries and/or source code, but does not provide a copy of the license text (in the source tree, or in some rare cases, anywhere), the packager should do their best to point out this confusion to upstream. This sometimes occurs when an upstream project's only reference to a license is in a README (where they simply say "licensed under the FOO license"), on their website, or when they simply do not check a copy of the license into their Source tree. Common licenses that require including their texts with all derivative works include ASL 2.0, EPL, BSD and MIT. Packagers should point out to upstream that by not including a proper full license text, they are making it difficult or impossible for anyone to comply with their desired license terms."

I don't think you have a licensing problem per se by not including the text of the licenses, but yes, it does make it harder for people redistributing your project to comply with the terms of the license. ASL 2.0 states "You must give any other recipients of the Work or Derivative Works a copy of this License; and...", and the text of the GPLv2 itself states "You should have received a copy of the GNU General Public License along with this program".

**Comment by nicolas-grekas** [comment]
So, I read the guidelines and the licenses on the subject, I'd prefer not bloating my source tree with full licenses... Given that I provide the HTTP link to the raw license wording, the risk that is mentioned Fedora (not choosing the right text) does not exist in our case. Would it be ok for you to package the licenses files yourselves? I've some other code packaged on Debian and they didn't require me to do anything special - but creating good code :)

**Comment by nicolas-grekas** [comment]
Since you made a PR, I merged it, thanks again.

**Comment by AdamWill** [comment]
I believe the issue with providing links to license text is that there's no way to be sure the links will always work - say someone finds the tarball lying around somewhere in ten years and the URLs have changed, what then? I agree it's kind of a bore, but hey. Thanks for the merge!
