### ISSUE TITLE
Not PSR-0 compliant

### ISSUE THREAD

**Issue by AdamWill** [tchwork/jsqueeze#11]
JSqueeze claims to be PSR-0 (in its composer.json), but it really isn't:

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

"A fully-qualified namespace and class must have the following structure `\<Vendor Name>\(<Namespace>\)*<Class Name>`"

that is, at least one level of namespacing is required, a top-level 'Vendor Name'. JSqueeze is a bare class. I'm now in an argument with my downstream package reviewer because our distribution guidelines don't allow us to put libraries directly in `/usr/share/php` (to avoid mess and conflicts - nothing else is called JSqueeze yet, but just today I found two things called cssmin, for instance...), but if I put it in a subdirectory, nothing will be able to autoload it without patching.

**Comment by nicolas-grekas** [comment]
v2.0.0 just released!
