### ISSUE TITLE
TypeError: n is not a function

### ISSUE THREAD

**Issue by DavidPrevot** [tchwork/jsqueeze#16]
Hi,

The following stanza from [js_tpl.js](https://github.com/owncloud/bookmarks/blob/master/js/3rdparty/js_tpl.js) is reduced in `(function(){var t={};this.tmpl=function n(n,i){var p=!/\W/.test(n)?t[n]=t[n]||n(document.getElementById(n).innerHTML):`:

    (function () {
        var cache = {};
        this.tmpl = function tmpl(str, data) {
                // Figure out if we're getting a template, or if we need to
                // load the template - and be sure to cache the result.
                var fn = !/\W/.test(str) ?
                                cache[str] = cache[str] ||
                                tmpl(document.getElementById(str).innerHTML) :

(Hopefully the quote is enough, the full  [js_tpl.js](https://github.com/owncloud/bookmarks/blob/master/js/3rdparty/js_tpl.js) is online anyway, and the fully minified JavaScript produced by JSqueeze is: `(function(){var t={};this.tmpl=function n(n,i){var p=!/\W/.test(n)?t[n]=t[n]||n(document.getElementById(n).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+n.replace(/[\r\t\n]/g," ").split("<&").join("\t").replace(/((^|&>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)&>/g,"',$1,'").split("\t").join("');").split("&>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return i?p(i):p}})();;`.)

The browser (well, firebug in console mode to get a hint on why the page is not properly loaded: empty content) throws `TypeError: n is not a function` and points to the following:

	...n n(n,i){var p=!/\W/.test(n)?t[n]=t[n]||n(document.getElementById(n).innerHTML):...
        ---------------------------------------^

This breaks the ability to use the bookmark application in ownCloud with JSqueeze. Thanks in advance if you manage to fix the issue or point to a workaround.

**Comment by nicolas-grekas** [comment]
This is definitely a bug on my side: the named function expression collides with the name of its first arg. I'll look for a fix, thanks for the report.

**Comment by nicolas-grekas** [comment]
Should be fixed in master, can you please confirm?

**Comment by DavidPrevot** [comment]
Thanks, the bookmark application is indeed back in ownCloud.
