### ISSUE TITLE
Javascript and PHP mixed

### ISSUE THREAD

**Issue by nolillo2003** [tchwork/jsqueeze#17]
First, sorry for my english.
I usually have Javascript mixed with PHP code, there any way to compress javascript code but not modify the code included between "<?php" and "?>"

Regards!
Manuel Soler.

**Comment by nicolas-grekas** [comment]
Yes, there is one: just echo the result of the `->squeeze(...)` method in place of you current javascript

**Comment by nolillo2003** [comment]
Thanks!!
