### ISSUE TITLE
jsqueeze breaks FlexSlider

### ISSUE THREAD

**Issue by giupenni** [tchwork/jsqueeze#20]
With jsqueeze the FlexSlider slideshow not work.

**Comment by nicolas-grekas** [comment]
Please help me (and yourself): can you provide me any links and/or error messages?

**Comment by giupenni** [comment]
With Firebug I can not found error messages. I noticed that FlexiSlider is loaded but the slideshow effects not work (no animations, not changes the slides) and the navigation controls are not displayed.

Unfortunately my dev site is in a local machine and I can not link it. The production site is this http://goo.gl/tZZyBA and work without problems with JSMin+ compressor.

Can I help you in other way? Any suggestions?

Thank you.

**Comment by nicolas-grekas** [comment]
So, if I understand well, compressing this file:
https://github.com/woothemes/FlexSlider/blob/master/jquery.flexslider.js
does not work?

**Comment by giupenni** [comment]
Exactly.
Il 27/mar/2015 13:58 "Nicolas Grekas" <notifications@github.com> ha scritto:

**Comment by giupenni** [comment]
The only error that I found is "TypeError: e(...).flexslider is not a function"

**Comment by nicolas-grekas** [comment]
I've tried with the demo in FlaxSlider's source code, all of them work with a jsqueezed file.
If you're working with JSqueeze v1, you should switch to v2.0.
Otherwise, I need more specific details, or better, a reproducer...
