### ISSUE TITLE
name of first function after comment may disappear, when keepImportantComments=true

### ISSUE THREAD

**Issue by rfool** [tchwork/jsqueeze#23]
Example input:

    /*! important comment */
    function first() {}
    function second() {}

When minifying this through JSqueeze with e.g. `$jz->squeeze($code,true,true,false)`, the name of the first function after an important comment disappears (and the output actually becomes invalid javascript).

Expected output:

    /*! important comment */
    function first(){};function second(){};

Actual output:

    /*! important comment */
    function(){};function second(){};

**Comment by nicolas-grekas** [comment]
Fix in https://github.com/tchwork/jsqueeze/commit/4cba99858bf94d20b48ba3a35d8a9e95c9beb07d
Thank you @rfool

**Comment by rfool** [comment]
That was fast. Thank you! ;)

**Comment by geekwright** [comment]
Any estimate on when this will be included in a tagged release? It works great, but is awkward to deploy.

Thanks!

**Comment by nicolas-grekas** [comment]
taggued, thanks for the reminder
