### ISSUE TITLE
regex ending interpreted as a comment

### ISSUE THREAD

**Issue by mmarinero** [tchwork/jsqueeze#24]
The following code gets broken on the 4th line. The ending //gi, is omitted and the next line joined likely because the parser understands it is a comment.

    respond.regex = {
        media: /@media[^\{]+\{([^\{\}]*\{[^\}\{]*\})+/gi,
        keyframes: /@(?:\-(?:o|moz|webkit)\-)?keyframes[^\{]+\{(?:[^\{\}]*\{[^\}\{]*\})+[^\}]*\}/gi,
        comments: /\/\*[^*]*\*+([^/][^*]*\*+)*\//gi,
        urls: /(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,
    };

Result (partial): 

    comments: /\/\*[^*]*\*+([^/][^*]*\*+)*\;urls:/ (url\()['"]?([^\/\)'

**Comment by nicolas-grekas** [comment]
Your regexp misses escaping one slash on the "comments" line: `...[^/]...` should be `...[^\/]...`
It looks like browser have more advanced parsers that do not require it to be escaped.
Still, this would require too much changes for a case that is easilly worked around.

**Comment by mmarinero** [comment]
Actually it's not my code but [Respond.js](https://github.com/scottjehl/Respond) I was trying to compress. But yeah, I missed the unescaped slash and thought it was a more general problem. The fix works.

**Comment by nicolas-grekas** [comment]
I suggest you open a PR on Respond.js, that would make their code more friendly to less advanced parsers...

**Comment by nicolas-grekas** [comment]
Easier than I first thought: see a1f756a

**Comment by mmarinero** [comment]
Yeah, works great now. Thank you.
