### ISSUE TITLE
Fix #15

### ISSUE THREAD

**Issue by exbit** [tchwork/jsqueeze#25]
https://github.com/tchwork/jsqueeze/commit/dc3c4073c2060d62a8578848c5d222a8b7608df1
after:
else if(a.iPage<=d){l=1;n=s}
else if(a.iPage>=(a.iTotalPages-d)){l=a.iTotalPages-s+1;n=a.iTotalPages}
always comes a new line, why?

**Comment by nicolas-grekas** [comment]
Is it an actual issue in your case? There is a technical reason that makes it easier this way with the current state of the parser, with no significant drawback (because you do gzip after minifying, don't you?)

**Comment by exbit** [comment]
original js: 56 files = 3,35 МБ (3 518 464 байт)
to https://github.com/tchwork/jsqueeze/commit/dc3c4073c2060d62a8578848c5d222a8b7608df1:
js min = 1,73 МБ (1 822 720 байт)
after https://github.com/tchwork/jsqueeze/commit/dc3c4073c2060d62a8578848c5d222a8b7608df1:
js min = 1,74 МБ (1 826 816 байт)
0.05%, but still. gzip used

**Comment by exbit** [comment]
may then add the option to minimize ExtJS, so you can disable the code: $code = preg_replace("'\}(?=(else|while)[^\$.a-zA-Z0-9_])'", "}\r", $code);

**Comment by nicolas-grekas** [comment]
Closing as "won't fix"
