### ISSUE TITLE
Problem with “const”

### ISSUE THREAD

**Issue by DavidPrevot** [tchwork/jsqueeze#27]
Hi,

The following simple test
``` js
const A = 0;
```
is transformed into
``` js
;const;A=0;
```
by JSqueeze (and thus breaks the “const” syntax), while it is properly transformed in
``` js
const A=0;
```
by uglifyjs.

**Comment by nicolas-grekas** [comment]
#28 should fix the issue

**Comment by DavidPrevot** [comment]
Indeed, thanks! It allows to go further with owncloud-music
minification, but is stuck again with another issue related to
angular.js (I’ll come back to you once I’ve time to debug it if there is
something that can be improved on JSqueeze side).

Regards

David

**Comment by nicolas-grekas** [comment]
Merged into master, let me know if you have a reproducer for the remaining issue

**Comment by DavidPrevot** [comment]
Hi,

Le 15/07/2015 10:43, Nicolas Grekas a écrit :
> #28 should fix the issue

Indeed, thanks! It allows to go further with owncloud-music
minification, but is stuck again with another issue related to
angular.js (I’ll come back to you once I’ve time to debug it if there is
something that can be improved on JSqueeze side).

Regards

David

**Comment by DavidPrevot** [comment]
> let me know if you have a reproducer for the remaining issue

Looks like the issue can be handled on the owncloud-music side: https://github.com/owncloud/music/pull/425 (I guess it would be nice to make JSqueeze more robust and able to deal with the improper yet widely —it’s not the first time I come across this kind of issue— used syntax, but well, the problem should soon be fixed at the root.)
