### ISSUE TITLE
Invalid output from https://github.com/johnny/jquery-sortable/blob/master/source/js/jquery-sortable.js

### ISSUE THREAD

**Issue by troymccabe** [tchwork/jsqueeze#31]
(I'll be able to dig through JSqueeze over the next couple days to try to submit a PR--just wanted to get this up before I forget :))

This issue is specifically here:
https://github.com/johnny/jquery-sortable/blob/master/source/js/jquery-sortable.js#L236

This generates the following (invalid) code: `{if(t.group===i)t.group=d++h[t.group]=new a(t)}`

Even removing the space before the increment operator, it still seemed to fail.

**Comment by nicolas-grekas** [comment]
This should be fixed in latest master, could you please confirm?
