### ISSUE TITLE
Fails to buil bootstrap-select.js

### ISSUE THREAD

**Issue by chris-mg** [tchwork/jsqueeze#40]
var args = arguments;
    // The arguments of the function are explicitly re-defined from the argument list, because the shift causes them
    // to get lost/corrupted in android 2.3 and IE9 #715 #775
    var _option = option,
    _event = event;
    [].shift.apply(args);
    
    var value;
    var chain = this.each(function () {

gets compiled to

`var o=arguments,s=n,a=i;[].shift.apply(o),value,chain=this.each(function(){`

but should be compiled to

`var o=arguments,s=n,a=i;[].shift.apply(o);var value,chain=this.each(function(){`

**Comment by benjR** [comment]
+1 our JS was broken too because of that.

**Comment by nicolas-grekas** [comment]
Can you please check #44?
