### ISSUE TITLE
Fails to build bootstrap.js

### ISSUE THREAD

**Issue by misotolar** [tchwork/jsqueeze#42]
#41 brokes *.offset declaration in [bootstrap.js](https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L1954-L1957):
```
  ScrollSpy.prototype.process = function () {
    var scrollTop    = this.$scrollElement.scrollTop() + this.options.offset
    var scrollHeight = this.getScrollHeight()
    var maxScroll    = this.options.offset + scrollHeight - this.$scrollElement.height()
```
compiled:
```
var n=this.$scrollElement.scrollTop()+this.options.offset var a=this.getScrollHeight(),s=this.options.offset +a-this.$scrollElement.height()
```

**Comment by glasset** [comment]
can confirm it's broken in v2.0.4 but work in v2.0.3 .

**Comment by nicolas-grekas** [comment]
Can you please check #44?

**Comment by glasset** [comment]
Thanks i have testing on my side, works well, can now re-compile [bootstrap.js](https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L1954-L1957)  with this #44
