### ISSUE TITLE
getter and setter are broken with variable mangling

### ISSUE THREAD

**Issue by callmemagnus** [tchwork/jsqueeze#43]
The following test case fails:
```js
function(coco) {

    function Test () {
        this.coco = coco;
    }

    Test.prototype = {
        get coco() {
            return this.coco;
        },
        set coco(newValue) {
            this.coco = newValue;
        }
    }

}('coco')
```
because of the variable replacement.

**Comment by nicolas-grekas** [comment]
True, this is not parsed as a closure right now... we should enhance the regexp that splits closures.
Would you like to give it a try?

**Comment by callmemagnus** [comment]
I'm trying but the code is not really the easiest to read.

Currently OoB, the result is:

```js
;function(o){function t(){this.coco=o};t.prototype={get o(){return this.coco},set o(newValue){this.coco=newValue}}}('coco')
```

I don't find where I can avoid these 2 cases to be counted as variables when preceded by "get " or "set ".

**Comment by nicolas-grekas** [comment]
I'll give it a try tomorrow

**Comment by Croydon** [comment]
Any updates on this? :)

**Comment by nicolas-grekas** [comment]
Can you please check #44?

**Comment by callmemagnus** [comment]
The version in #44 does not fix the mangling of the [g,s]et property when the name of the [g,s]etter is the same than a variable in an upper scope.

E.g.

```
(function(window, coco) {

    function Test () {
        this._coco = coco;
    }

    Test.prototype = {
        get coco() {
            return this._coco;
        },
        set coco(newValue) {
            this._coco = newValue;
        }
    }

    window.Test = Test;

})(window, 'coco');

var test = new window.Test();

test.coco();
```

get as output:

```
(function(c,t){function o(){this._coco=t};o.prototype={get t(){return this._coco},set t(t){this._coco=t}};c.Test=o})(window,'coco');var test=new window.Test();test.coco();
```
which obviously won't work as the getter "coco" does not exist: it is t in the closure.

**Comment by nicolas-grekas** [comment]
@callmemagnus should be fixed on master

**Comment by callmemagnus** [comment]
@nicolas-grekas yep working, thanks.

Do you plan a release?
